<?php

namespace ApptooMemb\MemberBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
	public function findContact($member)
	{
		$queryBuilder = $this->createQueryBuilder('c')
			->join('c.member', 'mb');
			
		return $queryBuilder->getQuery()->getResult();
	}

	public function isContact($member, $contact)
	{
		$queryBuilder = $this->createQueryBuilder('c')
			->where('c.member=:member')
			->andWhere('c.contact=:contact')
			->setParameter('member', $member)
			->setParameter('contact', $contact);

		return !empty($queryBuilder->getQuery()->getResult());
	}
}
