<?php

namespace ApptooMemb\MemberBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRepository extends EntityRepository
{
	public function findByUser($user) 
	{
		$fields = array('mb.id', 'mb.name', 'u.email', 'mb.address', 'mb.tel', 'mb.site');

		$queryBuilder = $this->createQueryBuilder('mb')
			->select($fields)
			->join('mb.user', 'u')
			->where('u.id = :user')
			->setParameter('user', $user);

		return $queryBuilder->getQuery()->getResult()[0];
	}

	public function findById($id)
	{
		$fields = array('mb.id', 'mb.name', 'u.email', 'mb.address', 'mb.tel', 'mb.site');

		$queryBuilder = $this->createQueryBuilder('mb')
			->select($fields)
			->join('mb.user', 'u')
			->where('mb.id = :id')
			->setParameter('id', $id);

		return $queryBuilder->getQuery()->getResult()[0];
	}

	public function getMemberId($memberName)
	{
		$fields = array('mb.id');

		$queryBuilder = $this->createQueryBuilder('mb')
			->select($fields)
			->where('mb.name = :name')
			->setParameter('name', $memberName);

		if(!empty($queryBuilder->getQuery()->getResult())) {
			return $queryBuilder->getQuery()->getResult()[0]['id'];
		}

		return 0;
	}
}
